// Auto-generated. Mirrors src/cli/thai-address-db.ts province table.
export interface ProvinceEntry { pvCode: string; nameTh: string; nameEn: string; }

export const PROVINCES: readonly ProvinceEntry[] = Object.freeze([
  Object.freeze({ pvCode: "81", nameTh: "กระบี่", nameEn: "Krabi" }),
  Object.freeze({ pvCode: "10", nameTh: "กรุงเทพมหานคร", nameEn: "Bangkok" }),
  Object.freeze({ pvCode: "71", nameTh: "กาญจนบุรี", nameEn: "Kanchanaburi" }),
  Object.freeze({ pvCode: "46", nameTh: "กาฬสินธุ์", nameEn: "Kalasin" }),
  Object.freeze({ pvCode: "62", nameTh: "กำแพงเพชร", nameEn: "Kamphaeng Phet" }),
  Object.freeze({ pvCode: "40", nameTh: "ขอนแก่น", nameEn: "Khon Kaen" }),
  Object.freeze({ pvCode: "22", nameTh: "จันทบุรี", nameEn: "Chanthaburi" }),
  Object.freeze({ pvCode: "24", nameTh: "ฉะเชิงเทรา", nameEn: "Chachoengsao" }),
  Object.freeze({ pvCode: "20", nameTh: "ชลบุรี", nameEn: "Chon Buri" }),
  Object.freeze({ pvCode: "18", nameTh: "ชัยนาท", nameEn: "Chai Nat" }),
  Object.freeze({ pvCode: "36", nameTh: "ชัยภูมิ", nameEn: "Chaiyaphum" }),
  Object.freeze({ pvCode: "86", nameTh: "ชุมพร", nameEn: "Chumphon" }),
  Object.freeze({ pvCode: "57", nameTh: "เชียงราย", nameEn: "Chiang Rai" }),
  Object.freeze({ pvCode: "50", nameTh: "เชียงใหม่", nameEn: "Chiang Mai" }),
  Object.freeze({ pvCode: "92", nameTh: "ตรัง", nameEn: "Trang" }),
  Object.freeze({ pvCode: "23", nameTh: "ตราด", nameEn: "Trat" }),
  Object.freeze({ pvCode: "63", nameTh: "ตาก", nameEn: "Tak" }),
  Object.freeze({ pvCode: "26", nameTh: "นครนายก", nameEn: "Nakhon Nayok" }),
  Object.freeze({ pvCode: "73", nameTh: "นครปฐม", nameEn: "Nakhon Pathom" }),
  Object.freeze({ pvCode: "48", nameTh: "นครพนม", nameEn: "Nakhon Phanom" }),
  Object.freeze({ pvCode: "30", nameTh: "นครราชสีมา", nameEn: "Nakhon Ratchasima" }),
  Object.freeze({ pvCode: "80", nameTh: "นครศรีธรรมราช", nameEn: "Nakhon Si Thammarat" }),
  Object.freeze({ pvCode: "60", nameTh: "นครสวรรค์", nameEn: "Nakhon Sawan" }),
  Object.freeze({ pvCode: "12", nameTh: "นนทบุรี", nameEn: "Nonthaburi" }),
  Object.freeze({ pvCode: "96", nameTh: "นราธิวาส", nameEn: "Narathiwat" }),
  Object.freeze({ pvCode: "55", nameTh: "น่าน", nameEn: "Nan" }),
  Object.freeze({ pvCode: "38", nameTh: "บึงกาฬ", nameEn: "Bueng Kan" }),
  Object.freeze({ pvCode: "31", nameTh: "บุรีรัมย์", nameEn: "Buri Ram" }),
  Object.freeze({ pvCode: "13", nameTh: "ปทุมธานี", nameEn: "Pathum Thani" }),
  Object.freeze({ pvCode: "77", nameTh: "ประจวบคีรีขันธ์", nameEn: "Prachuap Khiri Khan" }),
  Object.freeze({ pvCode: "25", nameTh: "ปราจีนบุรี", nameEn: "Prachin Buri" }),
  Object.freeze({ pvCode: "94", nameTh: "ปัตตานี", nameEn: "Pattani" }),
  Object.freeze({ pvCode: "14", nameTh: "พระนครศรีอยุธยา", nameEn: "Phra Nakhon Si Ayutthaya" }),
  Object.freeze({ pvCode: "56", nameTh: "พะเยา", nameEn: "Phayao" }),
  Object.freeze({ pvCode: "82", nameTh: "พังงา", nameEn: "Phang-Nga" }),
  Object.freeze({ pvCode: "93", nameTh: "พัทลุง", nameEn: "Phatthalung" }),
  Object.freeze({ pvCode: "66", nameTh: "พิจิตร", nameEn: "Phichit" }),
  Object.freeze({ pvCode: "65", nameTh: "พิษณุโลก", nameEn: "Phitsanulok" }),
  Object.freeze({ pvCode: "76", nameTh: "เพชรบุรี", nameEn: "Phetchaburi" }),
  Object.freeze({ pvCode: "67", nameTh: "เพชรบูรณ์", nameEn: "Phetchabun" }),
  Object.freeze({ pvCode: "54", nameTh: "แพร่", nameEn: "Phrae" }),
  Object.freeze({ pvCode: "83", nameTh: "ภูเก็ต", nameEn: "Phuket" }),
  Object.freeze({ pvCode: "44", nameTh: "มหาสารคาม", nameEn: "Maha Sarakham" }),
  Object.freeze({ pvCode: "49", nameTh: "มุกดาหาร", nameEn: "Mukdahan" }),
  Object.freeze({ pvCode: "58", nameTh: "แม่ฮ่องสอน", nameEn: "Mae Hong Son" }),
  Object.freeze({ pvCode: "35", nameTh: "ยโสธร", nameEn: "Yasothon" }),
  Object.freeze({ pvCode: "95", nameTh: "ยะลา", nameEn: "Yala" }),
  Object.freeze({ pvCode: "45", nameTh: "ร้อยเอ็ด", nameEn: "Roi Et" }),
  Object.freeze({ pvCode: "85", nameTh: "ระนอง", nameEn: "Ranong" }),
  Object.freeze({ pvCode: "21", nameTh: "ระยอง", nameEn: "Rayong" }),
  Object.freeze({ pvCode: "70", nameTh: "ราชบุรี", nameEn: "Ratchaburi" }),
  Object.freeze({ pvCode: "16", nameTh: "ลพบุรี", nameEn: "Lop Buri" }),
  Object.freeze({ pvCode: "52", nameTh: "ลำปาง", nameEn: "Lampang" }),
  Object.freeze({ pvCode: "51", nameTh: "ลำพูน", nameEn: "Lamphun" }),
  Object.freeze({ pvCode: "42", nameTh: "เลย", nameEn: "Loei" }),
  Object.freeze({ pvCode: "33", nameTh: "ศรีสะเกษ", nameEn: "Si Sa Ket" }),
  Object.freeze({ pvCode: "47", nameTh: "สกลนคร", nameEn: "Sakon Nakhon" }),
  Object.freeze({ pvCode: "90", nameTh: "สงขลา", nameEn: "Songkhla" }),
  Object.freeze({ pvCode: "91", nameTh: "สตูล", nameEn: "Satun" }),
  Object.freeze({ pvCode: "11", nameTh: "สมุทรปราการ", nameEn: "Samut Prakan" }),
  Object.freeze({ pvCode: "75", nameTh: "สมุทรสงคราม", nameEn: "Samut Songkhram" }),
  Object.freeze({ pvCode: "74", nameTh: "สมุทรสาคร", nameEn: "Samut Sakhon" }),
  Object.freeze({ pvCode: "27", nameTh: "สระแก้ว", nameEn: "Sa Kaeo" }),
  Object.freeze({ pvCode: "19", nameTh: "สระบุรี", nameEn: "Saraburi" }),
  Object.freeze({ pvCode: "17", nameTh: "สิงห์บุรี", nameEn: "Sing Buri" }),
  Object.freeze({ pvCode: "64", nameTh: "สุโขทัย", nameEn: "Sukhothai" }),
  Object.freeze({ pvCode: "72", nameTh: "สุพรรณบุรี", nameEn: "Suphan Buri" }),
  Object.freeze({ pvCode: "84", nameTh: "สุราษฎร์ธานี", nameEn: "Surat Thani" }),
  Object.freeze({ pvCode: "32", nameTh: "สุรินทร์", nameEn: "Surin" }),
  Object.freeze({ pvCode: "43", nameTh: "หนองคาย", nameEn: "Nong Khai" }),
  Object.freeze({ pvCode: "39", nameTh: "หนองบัวลำภู", nameEn: "Nong Bua Lam Phu" }),
  Object.freeze({ pvCode: "15", nameTh: "อ่างทอง", nameEn: "Ang Thong" }),
  Object.freeze({ pvCode: "37", nameTh: "อำนาจเจริญ", nameEn: "Amnat Charoen" }),
  Object.freeze({ pvCode: "41", nameTh: "อุดรธานี", nameEn: "Udon Thani" }),
  Object.freeze({ pvCode: "53", nameTh: "อุตรดิตถ์", nameEn: "Uttaradit" }),
  Object.freeze({ pvCode: "61", nameTh: "อุทัยธานี", nameEn: "Uthai Thani" }),
  Object.freeze({ pvCode: "34", nameTh: "อุบลราชธานี", nameEn: "Ubon Ratchathani" }),
]);
